### ISSUE TITLE
Negative value and no convergence for regularized Wasserstein distance between a measure and itself with parallel_dual__update=True 

### ISSUE THREAD

**Issue by theouscidda6** [google-research/ott#8]
# Issue overview

This issue describes a problem I encounter when trying to compute the regularized Wasserstein distance between a measurement with the `parallel_dual_update=True` feature in the `sinkhorn.sinkhorn` function of `ott.core`. 

# Code to reproduce experiment

The code to reproduce my experiment is:

```
rng = jax.random.PRNGKey(0) 
rngs = jax.random.split(rng, 3)

n = 100 # number of points in the support of the input and output measure
d = 2 # dimension of the points

x = jax.random.normal(rngs[0], (n,d)) # supports of the measures
unif = jnp.ones(len(x)) / len(x) # unfiorm weights

# define the geometry object
geom = pointcloud.PointCloud(x, x, epsilon=1e-2) 

# run the Sinkhorn algorithm for various maximal number of iterations and parallel_dual_updates=True 
max_iters = [100, 1000, 10000, 50000, 100000, 250000, 500000]
for max_iter in max_iters:
    out = sinkhorn.sinkhorn(geom=geom, a=unif, b=unif, threshold=1e-1, max_iterations=np.int(max_iter), parallel_dual_updates=True)
    print(f"max_iter={int(max_iter)}\nW_eps(alpha, alpha) = {out.reg_ot_cost}")
    print(f"Has Sinkhorn converged? {out.converged}\n")
```

# Why is there a problem ?

## Data generation
In this experiment, we start by generating 100 points in R^2 and we consider \alpha the uniform measure on these 100 points. We then want to calculate the regularized 2-Wasserstein distance W_ε between α and α, i.e. W_ε(α, α).

## Positivity of the regularized Wasserstein distance W_ε
By default, `OTT` considers the KL-divergence between the transport plane and the product of input and output measurements to regularize the Kantorovitch problem. In our case, the regularization is of the form KL(P | α x α). As this quantity is always positive and the scalar product between the cost and the transport plan is always positive because we use the Euclidean cost, the solution of this regularized Kantorovitch problem is positive as the min (reached) of a positive function. Thus, we have W_ε(α, α) > 0. Thus, when we compute W_ε(α, α) from `out = sinkhorn.sinkhorn(...)` of `ott.core`, we should have `out.reg_ot_cost > 0`.

## With `parrallel_dual_updates=False`
When we perform this calculation with `parrallel_dual_updates=False` in `out = sinkhorn.sinkhorn(...)`, we get a positive result and we converge (i.e. `out.converged=True`) for a reasonable `threshold` and `max_iterations`. 

## With `parrallel_dual_updates=True`
On the other hand, when we perform this calculation with `parrallel_dual_updates=True` in `out = sinkhorn.sinkhorn(...)`, we get a negative result and we do not converge (i.e. `out.converged=False`), even for a small `threshold` and a large `max_iterations`. The fact that it does not converge is reasonable, since the returned value is false. Precisely, by varying `max_iterations`, we oscillate slightly around the same negative value. This behavior can be found by executing the above code.

## Where does the bug seem to come from?
As described by [Fedy et. al, 2019], when we compute the regularized Wasserstein distance between a measure and itself, the regularized Kantorovitch dual problem becomes a concave maximization problem that is symmetric with respect to its two variables f and g. Hence, there exists a (unique) optimal dual pair (f,g = f) on the diagonal whose optimality (in the discrete setting) is expressed by a well-condition fixed point equation. In the same article, it is said that one can typically achieve convergence in about 3 iterations. The `parallel_dual_updates=True` feature seems to solve the problem by solving this fixed point equation only on f, rather than the classical Sinkhorn fixed point equation in f and g. The bug seems to come from solving this equation.

I hope to have helped you with this remark, and I thank you very much for the development of `OTT` which really facilitates the use of numerical optimal transport in ML pipeline.

**Comment by marcocuturicameto** [comment]
Thanks a lot Théo for the comment! I am looking into this and will come back to you very soon. It's true the `parallel_updates` option was tested only quite lightly (I think we only tested it on one test to check convergence was faster) but the unexpected behavior you are reporting suggests either an issue in the evaluation or in the method itself. Will get back to you shortly.

**Comment by marcocuturi** [comment]
Thanks again Théo for reporting this.

So, from my point of view, ``parallel_updates`` on its own, without some kind of averaging, does not work. If you look at the code, you will see it's only used once, and that is in [`sinkhorn_divergence.py`](https://github.com/google-research/ott/blob/152af172a066e0411e3a6e5dcb104ab97d412f01/ott/tools/sinkhorn_divergence.py#L107)

So if you add ``momentum_strategy=0.5`` everything seems to work (as in this [colab](https://colab.research.google.com/drive/1rD45sN0XJuvwhCA_vGvn5v_4d7ECRf83#scrollTo=KbstilxHxdIE) which, with the minor modification below,

```# run the Sinkhorn algorithm for various maximal number of iterations and parallel_dual_updates=True 
max_iters = [100, 1000, 10000]
for max_iter in max_iters:
  for momentum in [1.0, 0.5]:
      out = sinkhorn.sinkhorn(geom=geom, a=unif, b=unif, threshold=1e-1, max_iterations=max_iter, parallel_dual_updates=True, momentum_strategy=momentum)
      print(f"max_iter={int(max_iter)} and Momentum= {momentum} \n W_eps(alpha, alpha) = {out.reg_ot_cost}")
      print(f"Has Sinkhorn converged? {out.converged}\n")
```
outputs now

```
max_iter=100 and Momentum= 1.0 
 W_eps(alpha, alpha) = -1.1102707386016846
Has Sinkhorn converged? False

max_iter=100 and Momentum= 0.5 
 W_eps(alpha, alpha) = 0.044260770082473755
Has Sinkhorn converged? True

max_iter=1000 and Momentum= 1.0 
 W_eps(alpha, alpha) = -1.105759620666504
Has Sinkhorn converged? False

max_iter=1000 and Momentum= 0.5 
 W_eps(alpha, alpha) = 0.044260770082473755
Has Sinkhorn converged? True

max_iter=10000 and Momentum= 1.0 
 W_eps(alpha, alpha) = -1.1039981842041016
Has Sinkhorn converged? False

max_iter=10000 and Momentum= 0.5 
 W_eps(alpha, alpha) = 0.044260770082473755
Has Sinkhorn converged? True
```

**Comment by theouscidda6** [comment]
Ok, that makes sense, thank you very much for these explanations!
